table HistorN01
	lineageTag: c781ca45-7952-42c3-8920-a2b8dbb26ab8

	measure CosteAbsen€ = IF([CosteIT]+[CostePermiso]=0,BLANK(),[CosteIT]+[CostePermiso])
		formatString: #,0.00
		lineageTag: 29cf9725-e819-49d6-aa7d-36d2814be27d

	measure CosteIT = [Coste IT] + [ILT ENF]
		lineageTag: 80ce0816-9592-42c6-8475-1a2cd0510296

	measure CostePermiso = CALCULATE(SUM(HistorN01[hnimporte]),HistorN01[hnconcepto]=14)*1.3435
		lineageTag: c967a410-b490-4133-8d02-971c7ffc6c88

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Coste IT' =
			
			var acc = CALCULATE(SUM(HistorN01[hnimporte]),HistorN01[hnconcepto]=90014)
			var imp = CALCULATE(SUM(HistorN01[hnimporte]),HistorN01[hnconcepto]=90996)
			var enf1 = CALCULATE(SUM(HistorN01[hnimporte]),HistorN01[hnconcepto]=90012)
			var imp2 = CALCULATE(SUM(HistorN01[hnimporte]),HistorN01[hnconcepto]=90013)
			return
			acc+imp+enf1+imp2
		lineageTag: 13c19ff4-966e-4509-b88e-b01af7b3b7eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ILT ENF' = CALCULATE(SUM(HistorN01[hnimporte]),HistorN01[hnconcepto]=90011)
		lineageTag: 9e270118-dd9c-43ec-beb7-8ea728cb47ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% ABS' = DIVIDE([CosteAbsen€],[TotFraCN3])
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 1967cfbb-83e8-4679-bd34-9722927b823f

	column hncentro
		dataType: int64
		formatString: 0
		lineageTag: c2d71522-d462-44ae-b277-00a5c0eeaf29
		summarizeBy: sum
		sourceColumn: hncentro

		annotation SummarizationSetBy = Automatic

	column ctcliente
		dataType: int64
		formatString: 0
		lineageTag: 7c8caa1e-9792-47f1-a6b5-65db19242793
		summarizeBy: sum
		sourceColumn: ctcliente

		annotation SummarizationSetBy = Automatic

	column ctcpd
		dataType: int64
		formatString: 0
		lineageTag: 3eea5955-1ee4-49bd-b5cc-4507708b5cb4
		summarizeBy: sum
		sourceColumn: ctcpd

		annotation SummarizationSetBy = Automatic

	column hncontrato
		dataType: int64
		formatString: 0
		lineageTag: 87023620-84b9-4de0-84c0-8e401db1083b
		summarizeBy: sum
		sourceColumn: hncontrato

		annotation SummarizationSetBy = Automatic

	column cttrabajador
		dataType: int64
		formatString: 0
		lineageTag: 447d0e96-750c-4b46-b83c-1cd33a810459
		summarizeBy: sum
		sourceColumn: cttrabajador

		annotation SummarizationSetBy = Automatic

	column hnanyoliq
		dataType: int64
		formatString: 0
		lineageTag: 87def4c7-4f62-4802-9daa-3e9bac0bcecd
		summarizeBy: sum
		sourceColumn: hnanyoliq

		annotation SummarizationSetBy = Automatic

	column hnmesliq
		dataType: int64
		formatString: 0
		lineageTag: d1373708-fea5-4460-bb6c-d457f93167a2
		summarizeBy: sum
		sourceColumn: hnmesliq

		annotation SummarizationSetBy = Automatic

	column hntiponom
		dataType: string
		lineageTag: bae82d0f-789d-4f79-8f5d-c5baf9ef2956
		summarizeBy: none
		sourceColumn: hntiponom

		annotation SummarizationSetBy = Automatic

	column hnconcepto
		dataType: int64
		formatString: 0
		lineageTag: f68f7df6-cb02-4efc-8bfd-8346cae55cd3
		summarizeBy: sum
		sourceColumn: hnconcepto

		annotation SummarizationSetBy = Automatic

	column hnimporte
		dataType: double
		lineageTag: 99787c49-c4b6-4090-b052-f9840d135542
		summarizeBy: sum
		sourceColumn: hnimporte

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FechaH
		dataType: dateTime
		formatString: Long Date
		lineageTag: c2a64ccb-49f8-4fbb-af10-cf1bd0929dc2
		summarizeBy: none
		sourceColumn: FechaH

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HisCenCli = FORMAT(HistorN01[SuperCentroo],"00")&FORMAT(HistorN01[ClienteMioo],"000000")
		lineageTag: be926af8-f649-4da8-9e5b-fd15e74dba2f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Ccontratounido2 = FORMAT(HistorN01[hncentro],"00")&FORMAT(HistorN01[hncontrato],"00000000")&FORMAT(HistorN01[cttrabajador],"00000000")
		lineageTag: db585b6a-1851-4646-b931-9c81bf596ba3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column clcifdni
		dataType: string
		lineageTag: 0834d92c-7c9e-4e6b-85c6-b463f41c1552
		summarizeBy: none
		sourceColumn: clcifdni

		annotation SummarizationSetBy = Automatic

	column clcodigo
		dataType: int64
		formatString: 0
		lineageTag: 9eb5a177-3591-45f6-8b06-e0df4e8220e5
		summarizeBy: sum
		sourceColumn: clcodigo

		annotation SummarizationSetBy = Automatic

	column hnmicentro
		dataType: int64
		formatString: 0
		lineageTag: 40a2f401-68be-40e5-8668-62102c952d04
		summarizeBy: sum
		sourceColumn: hnmicentro

		annotation SummarizationSetBy = Automatic

	column ClienteMioo
		dataType: int64
		formatString: 0
		lineageTag: 510abc5d-7be3-4df2-9b23-abeb06f55033
		summarizeBy: sum
		sourceColumn: ClienteMioo

		annotation SummarizationSetBy = Automatic

	column SuperCentroo
		dataType: int64
		formatString: 0
		lineageTag: 0a3be209-6d2a-4708-aa79-469194adfecb
		summarizeBy: sum
		sourceColumn: SuperCentroo

		annotation SummarizationSetBy = Automatic

	partition HistorN01 = m
		mode: import
		source =
				let
				    Origen = Sql.Database("10.10.138.5\temporing", "no3001", [Query="select hncentro,ctcliente,ctcpd,hncontrato,cttrabajador,hnanyoliq,hnmesliq,hntiponom,hnconcepto,hnimporte#(lf)from hiscon inner join#(lf)      contra on hnempresa=ctempresa and hncentro=ctcentro and hncontrato=ctcontrato#(lf)where hnempresa=1#(lf)and hnanyoliq>=2021#(lf)and (hnconcepto=90900 or hnconcepto=90997 or hnconcepto=90011 or hnconcepto=90995 or hnconcepto=95000#(lf)or hnconcepto=90012 or hnconcepto=90013 or hnconcepto= 90014 or hnconcepto= 90015 or hnconcepto= 90996#(lf)or hnconcepto= 14 or hnconcepto= 295 or hnconcepto= 297 or hnconcepto= 91948 or hnconcepto= 90996#(lf)or hnconcepto= 94000 or hnconcepto= 94001 or hnconcepto= 94002 or hnconcepto= 94003 or hnconcepto= 94004#(lf)or hnconcepto= 94005#(lf))#(lf)and hntiponom='N'#(lf)"]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"hncentro", Int64.Type}, {"hnanyoliq", Int64.Type}, {"hnmesliq", Int64.Type}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Tipo cambiado", "FechaH", each Date.FromText("01/"&Number.ToText([hnmesliq])&"/"&Number.ToText([hnanyoliq]))),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada",{{"FechaH", type date}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Tipo cambiado1", {"hncentro", "ctcliente"}, Clientes, {"clcentro", "clcodigo"}, "Clientes", JoinKind.LeftOuter),
				    #"Se expandió Clientes" = Table.ExpandTableColumn(#"Consultas combinadas", "Clientes", {"clcifdni"}, {"clcifdni"}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Se expandió Clientes", "hnmicentro", each if (([hnanyoliq]=2024 and [hnmesliq]>2) or [hnanyoliq]>2024) and [hncentro]=71 then 22 else [hncentro]),
				    #"Consultas combinadas1" = Table.NestedJoin(#"Personalizada agregada1", {"hnmicentro", "clcifdni"}, Clientes, {"clcentro", "clcifdni"}, "Clientes", JoinKind.LeftOuter),
				    #"Se expandió Clientes1" = Table.ExpandTableColumn(#"Consultas combinadas1", "Clientes", {"clcodigo"}, {"clcodigo"}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Se expandió Clientes1",{{"hnmicentro", Int64.Type}}),
				    #"Personalizada agregada2" = Table.AddColumn(#"Tipo cambiado2", "ClienteMioo", each if [hnanyoliq]=2024 then (if [clcodigo]= 60492 then 160242 else (if [clcodigo]= 60378 then 160225 else (if [clcodigo]= 60280 then 160224 else (if [clcodigo]= 60422 then 160230 else (if [clcodigo]= 60461 then 160230 else (if [clcodigo]= 60306 then 160228 else (if [clcodigo]= 60449 then 160226 else (if [clcodigo]= 60292 then 160227 else (if [clcodigo]= 60433 then 160231 else (if [clcodigo]= 60388 then 160236 else [clcodigo])))))))))) else [clcodigo]),
				    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Personalizada agregada2",{{"ClienteMioo", Int64.Type}}),
				    #"Personalizada agregada3" = Table.AddColumn(#"Tipo cambiado3", "SuperCentroo", each if [ClienteMioo]=160228 or [ClienteMioo]=160230 or[ClienteMioo]=160227 or[ClienteMioo]=160231 or[ClienteMioo]=160236 or[ClienteMioo]=160226 or[ClienteMioo]=160224 or[ClienteMioo]=160225 or[ClienteMioo]=160242 then 16 else [hnmicentro]),
				    #"Tipo cambiado4" = Table.TransformColumnTypes(#"Personalizada agregada3",{{"SuperCentroo", Int64.Type}})
				in
				    #"Tipo cambiado4"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

