table Trabajadores
	lineageTag: 600743cc-dc9a-4a4a-bc21-700ccf1ab9cc

	column cttrabajador
		dataType: int64
		formatString: 0
		lineageTag: f5201701-a038-4828-a068-2e0bacfb2c1c
		summarizeBy: none
		sourceColumn: cttrabajador

		annotation SummarizationSetBy = Automatic

	column trsexo
		dataType: string
		lineageTag: 98b86b05-6fa8-42c3-82cd-67572a80d417
		summarizeBy: none
		sourceColumn: trsexo

		annotation SummarizationSetBy = Automatic

	column trfechanac
		dataType: dateTime
		formatString: Long Date
		lineageTag: 502755f8-646e-4f29-8ab5-fbbeca74e79c
		summarizeBy: none
		sourceColumn: trfechanac

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column trnacionalidad
		dataType: string
		lineageTag: 1ea04f0b-45f8-406e-9dbe-1d1e9017ed80
		summarizeBy: none
		sourceColumn: trnacionalidad

		annotation SummarizationSetBy = Automatic

	column Años
		dataType: double
		lineageTag: cb0ecd05-75ec-422c-b8c1-85110a67ae7b
		summarizeBy: none
		sourceColumn: Años

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trdiscapacidad
		dataType: int64
		formatString: 0
		lineageTag: 5bd5453c-ee71-498b-af6c-cf1da7f66c33
		summarizeBy: none
		sourceColumn: trdiscapacidad

		annotation SummarizationSetBy = Automatic

	partition Trabajadores-20b406c8-64f1-49f8-8a8a-4cfb55f7682d = m
		mode: import
		source =
				let
				    Source = Sql.Database("10.10.138.5\TEMPORING", "no3001", [Query="SELECT     distinct contra.cttrabajador,trabajador.trsexo,trabajador.trfechanac,trabajador.trnacionalidad,#(lf)            ((CONVERT(decimal (10,2), (GETDATE()-trabajador.trfechanac))))/365 as Años,trdiscapacidad#(lf)FROM         contra INNER JOIN#(lf)                      trabajador ON contra.ctempresa = trabajador.trempresa AND contra.cttrabajador =trabajador.trtrabajador inner join#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)  centros on contra.ctempresa=centros.ceempresa and contra.ctcentro=centros.cecentro#(lf)WHERE ctempresa=01#(lf)and ((contra.ctfechafinreal is null) or year(contra.ctfechafinreal)>=2021)"]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Source,{{"trfechanac", type date}, {"trdiscapacidad", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

