table Comentarios
	lineageTag: 0cf15b6e-aaa2-43f1-a64a-21975bcc1dfa

	column '¿Con qué delegación trabajas?'
		dataType: string
		lineageTag: 85e0a353-060c-4f90-b385-54a7878ab669
		summarizeBy: none
		sourceColumn: ¿Con qué delegación trabajas?

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: string
		lineageTag: 906b16ff-7d34-4891-9509-d90c4ee968ce
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column 'Persona de contacto en Temporing ETT'
		dataType: string
		lineageTag: 06c1b79d-ad44-44fd-a123-618b53fce686
		summarizeBy: none
		sourceColumn: Persona de contacto en Temporing ETT

		annotation SummarizationSetBy = Automatic

	column 'Puedes comentarnos las observaciones que consideres oportunas.'
		dataType: string
		lineageTag: ed22c0ec-b188-4275-95d2-30e5e9022571
		summarizeBy: none
		sourceColumn: Puedes comentarnos las observaciones que consideres oportunas.

		annotation SummarizationSetBy = Automatic

	column Del
		dataType: int64
		formatString: 0
		lineageTag: 496d014d-cf8c-468a-abef-4d95e0e33374
		summarizeBy: none
		sourceColumn: Del

		annotation SummarizationSetBy = Automatic

	column Texto
		dataType: string
		lineageTag: 7b576138-f907-468d-b4e4-befa0f041dd9
		summarizeBy: none
		sourceColumn: Texto

		annotation SummarizationSetBy = Automatic

	partition Comentarios = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("rVvNb9tIlv9XagIM0AOo7ST9NY3FHkpUWaZDkRqScseemUOJKttMUywNKXrinLaBBXbnMIfGnnZPm9vm0IfB3Oaq/2T/kv29VyQlJ5ajdG8QyJJY9arq1fv4vQ/9/vdPvnouvCh+Mngi6e9s86PE+7OAPsRKihcqSQLFz0MplB9H9PzJHwd7Zt5EqQrEpQr9dOdbWWqh8srqbu4XXwsZ+PQk8D0ZporejuMoUbF3JJIjeYQvUmMXttJi3OSl0eJOyHy5eWfwRJXi2pSm0oUwhahNdZtnuRWmFvPGlFasTIVPpViYtamWeakXtqYvr/ICYzK7tDRvYUSmq8qs86LAhBor6GKps827UoCIna+xxtK2RGtRmbop1kTraP8hghF/U65tiR39oXn69PnXIr1xR8GTZXOHDZQgvbYDkZrlylZ5eS3+Wag0pS1V5spUpsxyLcrG1GvM2rfYK7vMV7XeWW+iqzWY9eYxPge6Fp4twJVajG1x1W3Ss025ru6EVzTz90hufnI0Y1PoLN/8vRR0iGVT5ln7mZhrsrWuedmnz8VplKSYMZSxp4IIskNfKIiSTwLxxddPxZW1C1HbolnntqxJ6iQuBevLqugF5aOUPJlKfOtLMQ3k5t8gi/TFLLyghy/lua9icSbDzV8Opnhq19hHGA1noh+Bryd5kdN6JDz5AvJYG7Gyi2rzkxZZZXQlGggcbg13eGWrZcsY3ZR/agwGa7E2m79X4BhJJv4X4L+9guDSRWDSVhZWGlJPs2hIppe6gqjXJA63+HNrymtdkhBhRS3mGhvptAFk6rUuF5hRixs6CAu2k/hXWKCA0K2wh0ponr1qTLXWR/h3GHMS4kFUE4FTU5VYaitsH+csGwd/6CdkG0IVBPStwojpqQwvBiKeDVU4EBM/8AdiHEvPw5dnoKGCi3CAsSEOA92A/lR6yQeD6FV2Xpildp9wdTg830KRL1e5eaOPxLLJbphzGdhym4NZJLC1LYllOAMshq1E3axI4azIcmIK0as1rScsRut1fqsPO6eaxf5EjYVKphIGcNAZNDqXiKPfzdTBLAuMWJoqX2DPYp6VRLxem9WNLu/EWFewEmQoYVwEGZY5hh1GN61wmgKHfvmSzMNJpWFx6szS+8K8zueQ9oVeQB2nlb0ydZ0Tsw6jPW2KfP3GQEJIAOvdPR98blhMMcT5TGHJd4z81I/CrRYeRuS7LYndM4rYZCB/LDxdLcHXpJnnuN4a37zUkI5KnOly845NJWTAVguoaGvmwDFo59qQfK17hb3RZK4heqxyos7xpDLkj/hW4D40W8ySfAgLGeSq2rxdgcetxXwm/HB07yj4PEtSd5Jhbtd2Dmvszw2bkFaiAp1vTeXjJDy7uhPnuuAL8aq8hqPQYjY3i0MpjHR2A19LN6z/1OTiBIeBa4X3tAdSUIscSidUAVdRwbtkNV9pZcC9sa7rzd8PJHRCCoa/Yx+mAQrmxX6S+qEk2xErH38D//JAWomMZeLF8vLinmnbvG1t24mG09816YW93vwE9rWWvNjaElPe5sAHR4fdx9zcwqxcw6fOHzSqUwjbwtTXVSdd/TrkGyqTQUvJCELMvv3218K8hlEsrwn63EFQIeeZXmEqIRb6xpnJzVtsHAhGJHYOoSfL0ZJlJwR5hi8RAawdINBpXq90CZdRY7DhwSNgDnL7ZYeCnj8XQz+gY/rBUEZ0y8u5LnT5hUggZGyYQdh9+cqIhMb669e6ssdyUeW6PA4sAE8vhR8SHFf6yvZW1I0Wo9xc2/1zvMnlh2MDmEnzCmwFy8DPNTEAPhusXDOLWv7uISmzzFZ+eQv1FclK52W3o9BUjE/7c8BuuHUI05HaF86fw+pgzbl+pRctSN0ylkwL+fv+NnDPFlqCL/GUPfj9dUTNCEA4O86Y4dYBRsHmp9b7zjF7CUckYxHICXRmFMUSKFGeq2TrqoIoVqHcz14Ml+GI7KyQMV5Dhr39rNDCOpbXlk79SteDfsutZVyCF5r5r3dclxOoZ1+LsSKrjld5wqD6lLeYJCoVE8QhYzVRYUp7DWivcTSK/XGER3G6+WvYbfpDOl4qfChImRMooomAb/l1h5p7zPxbMfbP2Licsc/BmZSKxxfswcczQBgZjvF6ouKQmHC5d2aqvDBS4blMVAIWn8tYXfbbvk8LZMRZFI+VmKjL3838VB4d7aWLCAFoLyNRO7PVtTkWwWz/LhKFTYYiiMZkJD2BIOvc91QycLr4iWcaydDHwHEUXm5+CLDr2AeCi2V/rqB5IyamILHdS0S9zoqmzm+dbZhCrjOzYKh6nsMlb3mUXzdQ1M0PuLait+dfEDYkMvQnCuDuEz7mCWR6Iv0kkSKRM5ZSks+pjH3Pjz4yPbDXMGtFXjvd7h0T46u1mG/eHcEsitZbbd7VDj87bRVLW6wFkDpMrMiFpvAOuHMIDaXo1ORHYlxt/hvAsn5sD+cqmKXqpTgJIu8FqZvR6yp/A+1ZsUdgoLfrCO6hEJjJ0lIoW7NpwLNnTwe7KkfBVkZArhQwOeA92ZuSQDFhPdhEskJ1PqcgeYuqyXDdYkrdVNdQUuxg0WAlYCDC2pu/de7u4SNJeDh7rZdLwiwkbmfNIl/fELAkEHH0kVvxLOxtJWSztnpxg43esuaCMR+ZCIkMk5MonsC+JdApCgrjse/hQzobzgKoYtKLmQzA9Hi2Axn2HMZL/XN/JEdQ506dZCJG0IdzGQSbf9+S3A+R9uxXvQC1QH7u+bEXKKLu0UGV/HwqYQ8+P5sBBJ/iq1Od4dbpVtm8th7FuuinpmvByniGOFAgdASixeo1+bc6J8Cii2uSXJvpmuHMDec4QAlhhuV7Bw4hYnbHlbCktQs5iYP0kcuiHEnVBVi7smTYOS3tkjIdiLIW8OBlU2b6/ZQNuzbKr9grMgM7cbAWZX7rEjXkIgesV4zBBtDHf9TY84J2VgDplAusSymVTt61i+JKzuqIq5zUpXtGqy0MJq05iuTgz1w3edW553LR8pNYR1ipFIBh5cIpBuIhDocMHiG0YRrYGJFb2D4M7c9IDFxvYeEe0aobdzSOXAFZGrP5G3QGMBTBypufIVGnCHyqFan4b591UplQsL9DyHSEoGdwgQ1uvsMQQKW2cpeDqwUC1je2zUXtWRCRIq4fDNC4Q8Rdzsk+tO3OjrWSCq4i9oYY7fDWXTbDMkzlLNGtPRLYJxYpu9TYrsQNKCOTl7dk5HBXdOvPnj79NQVeDUBWZ/MemIkh5vWK0lcU47e49ptnYjwjUIPX6ezS48TnpDFsHYPmyvQwVsj8zSq3hdED4RCtiN5os9Y97Onwp4LY5Vebn7K8aPF7tZOWbOB9ruCDFsxCl6wA4CvyN5xcoowTAqdeSPqJhK6BM2H5b+GINm/rzjqQJNFrbUj6xMQpKbhamducY1BGjSsyBeAc0C3pNXmIzk19CYwYMpDGHxlHnEAcz2Q8gqmayM6kuzRbMiN800vlg3MpUJsCQYjUh+H85Okuvp7r721DaLkEZ/CNqEnMb/D8lYvfawgy60zSR+JrKBKYX68QdvIV3rGTJOhpKHPJjmX/wnOEUZlltegWBYKZi7rYXXXzttpJhz1IiNBIKgm/whOdyWGgxFDFk9lIJltWXEC/lD8miQkEPFkaicRXk2msBDzPZHYhhjMVRhh3Kj1AuzQaRXBIYholPlGcRrGQF6AZ///tpNsArT6NoxOV+AhpA+znot+cF4ViDIBOLvHjG1AF+AbDkgSE1c4cE5Pu6h6Z6IfYOkDeZ/COiKYvBScWVfKb94VJfMb7v0j4UeiH4xnCk/2EY4VTAC6nEngxxNH6gJ3O6eFkeLv18Y402TgYQGIGHTs6AdhErE98kilxFwxS9KWi/PuB9zFBxLP58Wco2CFUNj98lMxJTp46tZR7LndvpxNxQGFEUlADuNj1LhBhj9vGuy0MjaubG35PsZd2yuewslPDLgQuGG7oNafUneOBrSfoTBkQ56dp4GPHr8iuXhkGwy4B2dU3AOsfOsgjxBJd5dB3iokHnyahYxgcmFEEDLAWV+BEKzHvk2hN8vXOAcm+Nabcwgfmpr5rFo6nhF0coigfk2RDYygKceYcge+igd9z7Pd0iaNRXP7+vpgrWHJcmbuas3MwkM4T1y6JtAU/bvmvEXJRlguvsU9vQvNnMYQ91iQ3uyH25qc+xv5wlvS8KPbDc8SSAh7CDxHCCVcrcGOEVHE0nak0hkYNZSzP2E4hpvajZD/dNCHMfEYZ7Ewfn+mdMPKDsWBgOtn8axjCpM5CfyhfqG4vpD/qXFKOYfNXiWg2kDCWaUfry+fQd6qF4tXbTZa6YHJQH2nOVNgafLci1Le6qgBWH6jbdS6LckVQly49QiJxZUxBuLgFmLtR4BY0tw/bdNOSAjWmQkUTnRFCXjoEVDJqt3D8a1NRPEtCZ4tbEhog+ry+D67aQhZILwHuKG1TWhZLs8XcNXlaiHv1RnOJC2u2uLpoM29tiuepmMrJlCwn/rQFNl/RHSQGUaal2gaFIx1/H5yQztLUx/dJus1bJQpBXgQnFONKORnZpfnaNFxbcety8xmdpbScna8W0A5C9ABbLXgiVYMlzFesNquG1YAOuG7F/8GNTRBaLGDSik87zwt9RxLjzzfvKMfP2Bkam21T/A9OAwKIYeuVd0qH7pH++4zYT2Aox4EfRi+dlHdrgiVu772+fCtiNUvYTfIfXQNpako4AJHlr6lSuaL9AKVDOS5lsnfmOJ4BIwRqwkEEx7fCF3KbcPxgxhAGcw5D5vZI/QSenps3ut47AwoaEXIi80Apr1jS0X0X9bOsUEfDx3YaylNKjp1GE7XNFtybFzjnR67KeUEqz7rKLNd97CovO8i+1dLalvezvY4GR/CkWwDyucv8UqWY5bANrgYYglgForpk/7vDi8HOsjuW2rliDMHMjBxOxV630/SW+r5sz9HDjJlyARFiMs3L7zsXO9XZ94MWzz0U9012mh86hcyXq6JvI3BgglKCNHvgUAA+ntl6827bigBrVG9+ck8L3alqZjlmBdMqc7+ifgR6FPLZmjLqLj1Gm19w4N6GhFiIgId2f+56o4Yr6iotdYPhtlqa1m5g4GCX023JtC/ytdbuK5EM2bbJoRypgCT4PM/49lJblQ8VwWSX6eiT4wNXMOgzHVQggGO9KuyrfN3GLg+t5CfReRSkXUqUPKDwmrmu/0k8WHl7iIYHIAvnPIYehQljY87NyTiQj01L0glmeLPYTy86EfEBgoPAHwOgUriQxpHLQVPVDtYqSchW+SWX2yqWRirJ34mdvhnd+bg2fXD/puWaxJbyXB+kN1v1NF3nQOZubEAU4CgNRISW6fMNJAWm5hqLqYgE+I9IE3ffYV2XKOuVeM19GZAauzRrqu3yY0hNmzrbLw8xRZcMhyXnmQpu0ikXlAhpzdX25nrU8QUulTP8AC5cjiHkTjlPCsraugOr4hz+9xjwDqBMPzo71asrLvG6sTjaojLXunh00kSeBNF3LVSSszSayNQ/ZwQ9S5xV3429HqRx6p9FHDYq6pKIRCxJJi63jp0piakaxWosg0f3s43axBCYLomCn0Um9WOWxv4Q+4fG5nqpe671OvENxP+cnfG575pdsBcgWsTPo5mn2gJMcDFiyDgLOa0mFNzhNBKnM7jHyBH6LeWXGe0GKnQAEz4UgzjuTiSfdSRfRCmdDcxOZoEEeobWem1lZta5LkACUOgY3O/1gSUmEGVzpZfO4z428uR0J1S+t85jswLaYAph/WbXJffzJrmrbba+Ybl5+zpf6t3uCmjmtwNx5wIjWAZXnmA1p3iSOrQaQ8pN0FNXezdyquIhOOJ7JHxBsrMRgP3+BN+K82DkJgZyhIukDyPpnSYsA1M5DCKAmBRPwscnDS1sWinCBnYhMw21EhTUaLNoMg4bP4vh/qDthBoRwv6m12GKF4qdOOph8qdR7MkoEMlIjmBkI4f3IBHHYqhw6GPBe32cCIniGXmNkJQoacHhx+fJwG+zDzDvYxVw/QWugposZE9jIHhDA9rQ5i9bdn0pzhXVPfAKgaLYjrYih36oUsXmIUzU5keKdMnGnVOuxmVgRnEL92E8YbFaObh2gXjfS9nXM1r83yeZ20Dg6JFteFEQDKX/sk8E7az7yDSZWUqfT9hnu/YBQm6cG4d15dggA5J4nEqI8ISyGfdm5QdOEtNCQ0tOED6++TQCUTyi3Fp30veV+uEDx+MZ7otepjJ+se+cX34lzrnG5V49dRLBOoooacMa8BqcRnC3+VHtmUNJnlfk58UQGAbwjywq25FiTqgYfN/8jTu5Hpotg9SHDYQgqXDshxcqZpmF6UTUkBy6BR+mY3YSRaPdcuLH5wXcNR1RA4YYz+LhgdO4kMks2l3M0TuRBPOgI306ss/HDjgljDGTCJ6IKpg0Dp/HfVLy/YXkSQyUBr2Xh/IzfTGkbQXdUbqzbHtv9165c6/vwYT7g7+zdnFXt3vptpTp1Vr3EPkDwHfHXT4tRnT1EpdD4zHb4t/OqM4+3HF7eFOsm63RoOzZPRCJJd22uA5oKcvBHstyaiWvETQQ/S7+cgg0a7i8SIVaahcjJ9aDesqpUFMENxYAb7qdcTGHj7dTvDl6UKr+91/+E/FnRXHggt+LqQUm6YWlv8fybvM/e64lBPDYcefsm2fvzzZ7JoM1TUUPtbsm1//xDcaMecyYLYSn/JRaYoax78RFnQFKwb6E8kLumwU4lPotqt0t3R8wFaBUOUF+cPiXzzA85eGUMOBWxclQBvJMcWJFAafE/rbFBVBVEYCCegUyTnEWVypULiAhebxXyuQ6ZBvoLmzbCmpeZ/BUnELnBBVkKyty+uJo36bSIzE0BefuIJ1BM8+5O6/bFQfJMaSaEs/VOl9T7u2RM6abv3ghdzAAFXhpvPkP9wkhfggbkXxwXgy4f+B9lP3pZHdDBN/u7QhuevOPMs+s+MMTCmv/8ES02nGvVbtkHbvNN2/z91Il3MRNMV4fiLmOx3vB12dsFFz7vdANp8MRjuWleNUAFlz1aQcr+pFQwL6OgRup8jV0GMYEWruwv9l3XnmRuMAn8nww6cMr+YAD+ygBio74q/dl7CMcv6R8jjjP1wiDdRfrW5z7AXlQNQmjpe6ItUta3XFMbbPNOzCaedHiJa41dD9I4aSKa75fO87t241nKUlM5tL1+mIotcuOYTsMQ5B9W9vLYG6hjSd+Cv/XdfC0cVRKqcTxLGXwsU8190pqVxepe+Zd5qt7O3xk9k4rMIcZpX5F6fCjgi7/FV9+5S6/OOSUMNwr7sGCU3v+9OmXjoghGpwsq/KqI9F6EXic1pnhfYFhMC4lZ7j6Vq9KU5s5JwsHnJRvdAE7BeeS6Zo9Tm3JmZEfcvaH7vgKtoqK4vu2eq++Iah5jthQf+xqn34lLsd0H5cyluPoUorP5O1CHwEeL6p8QZEOeQYZbFsAQaPvpEC8sHlbzXWFd10P+6eQDhHzXxJ04l+5KUT2FODAwF9+AhXAxPvdZZ2yq2TzX/i0+eFTKSIKXBsKs89M3dQi0V3Pz6EEuh7ThH7+EFIPAOwRBiPGd4DsAuC4XGhqtVxQT2X1CcTlKAZOnCIIZPTZGpeu5b7LJxxTUY7qcrQwYgFxfBEF/GZKJm084yD50DXbsLrNKXW9dm3ufuY4tflH3fdHHXfScBybucn0cScnbXP5MYsRW6byKqeq7EBQYbK6X9Qk3Hg4W2CTI3EacvnxlxzWiyaKeBgIGSBGpt4JGhr+QrInCvIZ/wJBVzVVv8z6Fwhm/EUYncuUEnrKu/ACTiI7dfklRyP9G0ffRTHnH/YK9/NnROk+KY8qVkyKrNSVLeodeXvClSaSG5eH1Z9OaUJp2sy6Pi0ymVxpJ8+u7xzCcckobhF0P5DgnwzmwD2vOGZhgK/drwHcT9DIT7Pz5YihKroetcN35VPqhEEeNYB3Degw5RPqOh9xQlOOYzlSHrQOktgmIV2U2PW0UE5xMqWfkrYwp2tPGgiOZ8MTnzIzlHwGheQEl3oZIbqG7Hlw15Tsph+hcr8SddAS1KRM0YUrBUBO1GTqMkf89HczqAKlGGDOQqpxhm7cJEqORDITXOMT3KczUTgHNzG1/VCOvkymODQNVy89yn1hdXe0X/3qE1kI0xeomDp/1Wgsd4uBF8Kx8ucIS/V9YeCUJ7rU14ac9BMuBuV6Kc5stdDlpxOFW0eoW5HPTWzJKZ4L25ZR5hy9UcucXuf1laEGAApGljnEruBmEf784C9JDt7BCQV2/HtjTulPVIhIao/KD7lcef/XxG1pkLoaPzDPuEnGMJS2067uR4q6oCLYALhWX9Mvl/ocsPu1J0Lp/JZCL9dcC7jUdL/PzfCWk4Z9X4OrIiJsY2jEoRY1/1JHTm46B/EJpmUXKf3y2z0jbKt6c84/xEBUu/1dyV67evgaAVWjRGper/Pi/o7hbl0AwaiTm1l6e1YKn+7LJSoWNmuWrv+IfzgJo0YJ+lvKW/zx/wA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Texto = _t, #"¿Con qué delegación trabajas?" = _t, Cliente = _t, #"Persona de contacto en Temporing ETT" = _t, #"Puedes comentarnos las observaciones que consideres oportunas." = _t]),
				    #"Dividir columna por delimitador" = Table.SplitColumn(Origen, "Texto", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"Texto.1", "Texto.2"}),
				    #"Filas filtradas" = Table.SelectRows(#"Dividir columna por delimitador", each true),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Filas filtradas",{{"Texto.1", "Del"}, {"Texto.2", "Texto"}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Del", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

