table 'Agrupación xCNAE'
	lineageTag: 1f315efa-e7e4-444e-b854-2090476a3888

	column cna2d
		dataType: int64
		formatString: 0
		lineageTag: 97fb278a-7fb4-408d-84aa-1a47f506ccb0
		summarizeBy: none
		sourceColumn: cna2d

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: dd78fba8-5196-4872-8e7d-1e75d9b16058
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Agrupación
		dataType: int64
		formatString: 0
		lineageTag: 2e4a0358-46bd-4fa7-a8cc-a69beac5c4c0
		summarizeBy: none
		sourceColumn: Agrupación

		annotation SummarizationSetBy = Automatic

	partition 'Agrupación xCNAE-1cfb3883-d427-4cea-88c6-9cae57f2a9e0' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("\\10.10.138.5\Excels PBIs\Facturac x CNAE.xlsx"), null, true),
				    #"Agrupación x CNAE_Sheet" = Origen{[Item="Agrupación x CNAE",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Agrupación x CNAE_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Nº", Int64.Type}, {"Acum orden", type number}, {"Sum %", type number}, {"cna2d", Int64.Type}, {"Nombre", type text}, {"TotFra", type number}, {"%", type number}, {"Sum%", type number}, {"Horas Realizadas", type number}, {"FraXHora", type number}, {"Agrupación", Int64.Type}, {"Column12", type any}, {"Column13", type text}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}}),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Tipo cambiado",{"cna2d", "Nombre", "Agrupación"}),
				    #"Filas filtradas" = Table.SelectRows(#"Otras columnas quitadas", each ([cna2d] <> null))
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

