table Agrupación
	lineageTag: 9107f854-1bfe-4c21-bf46-aa46a949c48c

	column Agrupación
		dataType: int64
		formatString: 0
		lineageTag: 9bc1637a-ad04-42e1-90d6-24454278e676
		summarizeBy: none
		sourceColumn: Agrupación

		annotation SummarizationSetBy = Automatic

	column 'Sectores de Actividad'
		dataType: string
		lineageTag: bdf7ce6c-165d-4f86-b0e7-5b77963c6035
		summarizeBy: none
		sourceColumn: Sectores de Actividad

		annotation SummarizationSetBy = Automatic

	partition Agrupación-211db1cb-5618-4910-93a8-42c672f6ab00 = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("\\10.10.138.5\Excels PBIs\Facturac x CNAE.xlsx"), null, true),
				    Hoja1_Sheet = Origen{[Item="Hoja1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Hoja1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Agrupación", Int64.Type}, {"Sectores de Actividad", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

