table CipHoras
	lineageTag: d07a1a03-b946-4847-8af3-f9a501fbec7c

	measure TotH10 = SUM(CipHoras[mrhoras10])
		lineageTag: 0ae9c11e-5b08-46ae-8dbb-149cb4413559

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotHNormales = SUM(CipHoras[Horas normales])
		lineageTag: 601eae9e-89a3-42b2-841c-0fdbaccd35ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotHNoctNorm = SUM(CipHoras[Nocturno normal])
		lineageTag: 456084ee-3402-4aef-92ec-136eeaaa576e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotHExtraNorm = SUM(CipHoras[Extra normal])
		lineageTag: 57f0b025-01fb-4674-946f-16adf73ac33d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotHExtraSab = SUM(CipHoras[Extra sábado])
		lineageTag: a58dce9e-d54d-4e13-a564-c2c7b9870a7b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotHExtraFest = SUM(CipHoras[Extra festivo])
		lineageTag: 5d7a0111-1dd8-432f-acbc-dc37e9b40465

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotHNoctExtra = SUM(CipHoras[Nocturno extra])
		lineageTag: 26401c06-1a1f-4145-a509-7ea1539dd7d4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotHNoctSab = SUM(CipHoras[Nocturno sábado])
		lineageTag: 58d2445c-e6e9-462b-b86f-b4e07c213300

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotHNoctFest = SUM(CipHoras[Nocturno festivo])
		lineageTag: 1f3512b2-5ecc-49b8-9228-d6b4eda654c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotHComp = SUM(CipHoras[Horas compensacion])
		lineageTag: 06e9baf1-2f12-4085-a665-aa5a71df611b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TotH Net4' = SUM(CipHoras[mrhorpres])
		formatString: 0.00
		lineageTag: 75c5db91-f729-446a-9f5a-477fb2cbf524

	measure TotHInci = SUM(CipHoras[mrhorinci])
		formatString: 0.00
		lineageTag: 48e98f17-83a9-4bdc-852a-c479c6a59c59

	column mrcentro
		dataType: int64
		formatString: 0
		lineageTag: 084e8efe-2333-4c24-bfc1-290d009cfbdd
		summarizeBy: sum
		sourceColumn: mrcentro

		annotation SummarizationSetBy = Automatic

	column mrcliente
		dataType: int64
		formatString: 0
		lineageTag: dee34eaf-bd14-407a-8631-36699a658558
		summarizeBy: sum
		sourceColumn: mrcliente

		annotation SummarizationSetBy = Automatic

	column mrcentrocli
		dataType: int64
		formatString: 0
		lineageTag: 837e7689-bdbc-4539-ac2a-bb63fab3c006
		summarizeBy: sum
		sourceColumn: mrcentrocli

		annotation SummarizationSetBy = Automatic

	column mrfecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0ed5b163-cefb-4e80-b7e9-971f4db79680
		summarizeBy: none
		sourceColumn: mrfecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column mrproductor
		dataType: int64
		formatString: 0
		lineageTag: 52a4f15e-729d-4a47-8964-bf92c395548b
		summarizeBy: none
		sourceColumn: mrproductor

		annotation SummarizationSetBy = Automatic

	column mrdesder
		dataType: double
		lineageTag: 70ba650f-b1e1-4d8c-8a33-7c98465e387d
		summarizeBy: sum
		sourceColumn: mrdesder

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mrhastar
		dataType: double
		lineageTag: 587f8c2b-4772-4c88-9633-86d18794af7f
		summarizeBy: sum
		sourceColumn: mrhastar

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mrhorpres
		dataType: double
		lineageTag: 1dc41a68-ed7f-4db6-87a9-f368b85d9daf
		summarizeBy: sum
		sourceColumn: mrhorpres

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mrhorinci
		dataType: double
		lineageTag: fa925fff-6007-466b-bab8-b5de9825924a
		summarizeBy: sum
		sourceColumn: mrhorinci

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mrinci
		dataType: int64
		formatString: 0
		lineageTag: 45a94cc3-f068-4f95-9d14-50179de2a4a1
		summarizeBy: sum
		sourceColumn: mrinci

		annotation SummarizationSetBy = Automatic

	column mrhoras10
		dataType: double
		lineageTag: 58d038fc-5f67-42e8-8f58-6aef432e5062
		summarizeBy: sum
		sourceColumn: mrhoras10

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Horas normales'
		dataType: double
		lineageTag: 9a57fdbd-8a5c-4e7e-aec0-68c0f2d00d8c
		summarizeBy: sum
		sourceColumn: Horas normales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nocturno normal'
		dataType: double
		lineageTag: c7787598-8dd7-471f-a183-166e59f0ab8a
		summarizeBy: sum
		sourceColumn: Nocturno normal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Extra normal'
		dataType: double
		lineageTag: 67fb3830-e588-42ae-a81b-6e9dc8ce3748
		summarizeBy: sum
		sourceColumn: Extra normal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Extra sábado'
		dataType: double
		lineageTag: 8ce9a14f-dff4-4289-9678-f00878ce5137
		summarizeBy: sum
		sourceColumn: Extra sábado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Extra festivo'
		dataType: double
		lineageTag: 11034efc-4631-4f47-8c80-551f142e25db
		summarizeBy: sum
		sourceColumn: Extra festivo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nocturno extra'
		dataType: double
		lineageTag: c43f4178-ff36-4069-8a9a-7828c0c1d137
		summarizeBy: sum
		sourceColumn: Nocturno extra

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nocturno sábado'
		dataType: double
		lineageTag: 43ac741a-d1c4-4d54-8aef-7c2cae1f25ba
		summarizeBy: sum
		sourceColumn: Nocturno sábado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nocturno festivo'
		dataType: double
		lineageTag: 9b102011-0425-4bcb-b921-1f2dc6c05700
		summarizeBy: sum
		sourceColumn: Nocturno festivo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Horas compensacion'
		dataType: double
		lineageTag: 9e2c2c4a-6249-4b0b-befa-598d7ac570a7
		summarizeBy: sum
		sourceColumn: Horas compensacion

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HDesde
		dataType: dateTime
		formatString: Long Time
		lineageTag: e2e71f1b-e9a5-43eb-89fd-437370c8624c
		summarizeBy: none
		sourceColumn: HDesde

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column HHasta
		dataType: dateTime
		formatString: Long Time
		lineageTag: 7803d458-5a34-452e-8818-f7e3d3338a4a
		summarizeBy: none
		sourceColumn: HHasta

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition CipHoras = m
		mode: import
		source =
				let
				    Origen = Sql.Database("10.10.138.5\temporing", "no3001", [Query=" SELECT #(lf)    mrcentro,#(lf)    mrcliente,#(lf)    mrcentrocli,#(lf)    mrfecha,#(lf)    mrproductor,#(lf)    mrdesder,#(lf)    mrhastar,#(lf)    mrhorpres,#(lf)    mrhorinci,#(lf)    mrinci,#(lf)    mrhoras01 AS [Horas normales],#(lf)    mrhoras02 AS [Nocturno normal],#(lf)    mrhoras03 AS [Extra normal],#(lf)    mrhoras04 AS [Extra sábado],#(lf)    mrhoras05 AS [Extra festivo],#(lf)    mrhoras06 AS [Nocturno extra],#(lf)    mrhoras07 AS [Nocturno sábado],#(lf)    mrhoras08 AS [Nocturno festivo],#(lf)    mrhoras09 AS [Horas compensacion],#(lf)    mrhoras10#(lf)FROM [no3001].[dbo].[cpmarcaje]#(lf)WHERE mrempresa = 1#(lf)  AND mrcentro = 9#(lf)  AND mrcliente = 90318#(lf)  AND mrfecha >= '2026-01-01';"]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"mrcentro", Int64.Type}, {"mrcentrocli", Int64.Type}, {"mrfecha", type date}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Tipo cambiado", "HDesde", each #time(
				    Number.From(Number.IntegerDivide([mrdesder], 1)),
				    Number.Round(([mrdesder] - Number.IntegerDivide([mrdesder], 1)) * 100, 0),
				    0
				)),
				    #"Personalizada agregada1" = Table.AddColumn(#"Personalizada agregada", "HHasta", each #time(
				    Number.From(Number.IntegerDivide([mrhastar], 1)),
				    Number.Round(([mrhastar] - Number.IntegerDivide([mrhastar], 1)) * 100, 0),
				    0
				)),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada1",{{"HDesde", type time}, {"HHasta", type time}})
				in
				    #"Tipo cambiado1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

